name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      version: 1.1.${{ github.run_number }}
      patchVersion: ${{ github.run_number }}

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      # could also use gradle wrapper task https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
      - name: Build extension
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build -PBUILD_NUMBER=${{ env.patchVersion }} -PBUILD_SOURCEBRANCH=$GITHUB_REF_NAME -PBUILD_SOURCEVERSION=$GITHUB_SHA -PPACKAGE_VERSION=${{ env.version }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: semantic-version-extension-v${{ env.version }}
          path: build/distributions/*.zip
          retention-days: 1
